heat_template_version: '2013-05-23'

parameters:
  name:
    type: string
    description: Name of the VM

  net_name:
    type: string
    description: Name of network

  subnet_name:
    type: string
    description: Name of subnet

  flavor_name:
    type: string
    description: Name of the flavor

resources:
  server1_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: net_name }
      security_groups: [ ssh-ping, default ]
      fixed_ips:
        - subnet_id: { get_param: subnet_name }

  server1_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: provider
      port_id: { get_resource: server1_port }

  server1:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: cirros
      flavor: { get_param: flavor_name }
      networks:
        - port: { get_resource: server1_port }

outputs:
  server1_private_ip:
    description: Private IP address of server1
    value: { get_attr: [ server1, first_address ] }
  server1_public_ip:
    description: Floating IP address of server1
    value: { get_attr: [ server1_floating_ip, floating_ip_address ] }